### PR TITLE
problem

### PR DESCRIPTION
**Pull request by ghost**
pb

Hello I can not compile with your files and I do not understand the error is what could someone please help me?
I use contiki 2-7

### CODE REVIEW

**Comment by dak664** [comment]
You need the java msp emulator to compile msp motes. Look elsewhere for current code, this mirror should not be separately modified.

**Comment by ghost** [comment]
Sorry I don't understand. I am beginner and I will wish simply to communicate my mote MicaZ between them with cooja

**Comment by dak664** [comment]
Cooja does a java simulation of radio messages between motes.  Contiki examples can be compiled to run on the host computer. "Native" Cooja motes are these CPU processes which interact with Cooja through the java runtime library.  A contiki process generates a message and writes it to a java input buffer in Cooja, which copies it to the destination process.
Cooja also allows emulation of actual hardware by loading a microprocessor .elf files into a simulator, but the repository does not include those third party tools.  Micaz neds the mps toolchain and simulator which is included in Instant Contiki.  Suggest you start there, http://www.contiki-os.org/start.html

**Comment by ghost** [comment]
I have already looked at this site but I don't have the mote MicaZ and I have already done several tests with the sky mote to understand their operation.
Can you give me a link that will allow me to download this .elf file or a link to a tutorial allowing me to use RPL on cooja with the MicaZ mote please
I only have two weeks left to complete this internship and I have to pass it to validate my studies...
Thank you for your help

**Comment by ghost** [comment]
please ?

**Comment by ghost** [comment]
Hello please could you help me ?

**Comment by dak664** [comment]
Your only hope is an instant contiki from around 2012, maybe 2.5
https://sourceforge.net/projects/contiki/files/Instant%20Contiki/

**Pull request closed without merging**
